/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author S
 */
public class Snack extends javax.swing.JFrame {

    /**
     * Creates new form Snack
     */
    public Snack() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        lbl1 = new javax.swing.JLabel();
        moneytf = new java.awt.TextField();
        lbl3 = new java.awt.Label();
        label1 = new java.awt.Label();
        changetf = new java.awt.TextField();
        jPanel1 = new javax.swing.JPanel();
        chocorb = new javax.swing.JRadioButton();
        latterb = new javax.swing.JRadioButton();
        waterrb = new javax.swing.JRadioButton();
        applerb = new javax.swing.JRadioButton();
        vanillarb = new javax.swing.JRadioButton();
        graperb = new javax.swing.JRadioButton();
        purchasebtn = new javax.swing.JButton();
        clearbtn = new javax.swing.JButton();
        cancelbtn = new javax.swing.JButton();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Snack Station");
        setBackground(new java.awt.Color(204, 255, 204));

        lbl1.setBackground(new java.awt.Color(153, 153, 255));
        lbl1.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 24)); // NOI18N
        lbl1.setForeground(new java.awt.Color(153, 153, 255));
        lbl1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl1.setText("Snack Station");

        moneytf.setBackground(new java.awt.Color(255, 255, 255));
        moneytf.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        lbl3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lbl3.setForeground(new java.awt.Color(0, 0, 153));
        lbl3.setName(""); // NOI18N
        lbl3.setText("Insert Money");

        label1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label1.setForeground(new java.awt.Color(0, 0, 153));
        label1.setText("Change");

        changetf.setBackground(new java.awt.Color(255, 255, 255));
        changetf.setEditable(false);
        changetf.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        changetf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changetfActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Select Item", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14), new java.awt.Color(0, 153, 0))); // NOI18N

        chocorb.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        chocorb.setForeground(new java.awt.Color(0, 0, 0));
        chocorb.setText("Chocolate Milk $1.25");
        chocorb.setName(""); // NOI18N
        chocorb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chocorbActionPerformed(evt);
            }
        });

        latterb.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        latterb.setForeground(new java.awt.Color(0, 0, 0));
        latterb.setText("Latte $1.25");
        latterb.setName("radiob2"); // NOI18N
        latterb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                latterbActionPerformed(evt);
            }
        });

        waterrb.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        waterrb.setForeground(new java.awt.Color(0, 0, 0));
        waterrb.setText("Water $1.00");
        waterrb.setName("radiob3"); // NOI18N
        waterrb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                waterrbActionPerformed(evt);
            }
        });

        applerb.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        applerb.setForeground(new java.awt.Color(0, 0, 0));
        applerb.setText("Apple Juice $1.50");
        applerb.setName("applerb"); // NOI18N
        applerb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applerbActionPerformed(evt);
            }
        });

        vanillarb.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        vanillarb.setForeground(new java.awt.Color(0, 0, 0));
        vanillarb.setText("Vanilla Milk $1.05");
        vanillarb.setName("radiob5"); // NOI18N
        vanillarb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vanillarbActionPerformed(evt);
            }
        });

        graperb.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        graperb.setForeground(new java.awt.Color(0, 0, 0));
        graperb.setText("Grape Juice $2.00");
        graperb.setName("radiob6"); // NOI18N
        graperb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                graperbActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(applerb)
                    .addComponent(chocorb))
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(vanillarb)
                    .addComponent(latterb))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(graperb)
                    .addComponent(waterrb))
                .addGap(44, 44, 44))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chocorb)
                    .addComponent(latterb)
                    .addComponent(waterrb))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(applerb)
                    .addComponent(vanillarb)
                    .addComponent(graperb))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        purchasebtn.setBackground(new java.awt.Color(204, 0, 0));
        purchasebtn.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        purchasebtn.setText("Purchase");

        clearbtn.setBackground(new java.awt.Color(204, 0, 0));
        clearbtn.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        clearbtn.setText("Clear");
        clearbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearbtnActionPerformed(evt);
            }
        });

        cancelbtn.setBackground(new java.awt.Color(204, 0, 0));
        cancelbtn.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        cancelbtn.setText("Cancel");
        cancelbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(lbl3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(moneytf, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(changetf, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(39, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(148, 148, 148))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(purchasebtn)
                .addGap(114, 114, 114)
                .addComponent(clearbtn)
                .addGap(127, 127, 127)
                .addComponent(cancelbtn)
                .addGap(100, 100, 100))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(moneytf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(changetf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(purchasebtn)
                    .addComponent(clearbtn)
                    .addComponent(cancelbtn))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleDescription("Snack Station");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void latterbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_latterbActionPerformed
        // TODO add your handling code here:
       if(latterb.isSelected()){
       chocorb.setSelected(false);
       waterrb.setSelected(false);
       applerb.setSelected(false);
       vanillarb.setSelected(false);
       graperb.setSelected(false);
       } 
       
    }//GEN-LAST:event_latterbActionPerformed

    private void changetfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changetfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_changetfActionPerformed

    private void cancelbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelbtnActionPerformed
        // cancel selection
        System.exit(0);
        
    }//GEN-LAST:event_cancelbtnActionPerformed

    private void clearbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearbtnActionPerformed
        // clears the all selection and text field
        chocorb.setSelected(false);
        latterb.setSelected(false);
        waterrb.setSelected(false);
        applerb.setSelected(false);
        vanillarb.setSelected(false);
        graperb.setSelected(false);
        moneytf.setText(" ");
        changetf.setText(" ");
    }//GEN-LAST:event_clearbtnActionPerformed

    private void chocorbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chocorbActionPerformed
        // changing radio buttons to select only one
        if (chocorb.isSelected()){
            latterb.setSelected(false);
            waterrb.setSelected(false);
            applerb.setSelected(false);
            vanillarb.setSelected(false);
            graperb.setSelected(false);
        }
    }//GEN-LAST:event_chocorbActionPerformed

    private void waterrbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_waterrbActionPerformed
        // TODO add your handling code here:
        if(waterrb.isSelected()){
        chocorb.setSelected(false);
        latterb.setSelected(false);
        applerb.setSelected(false);
        vanillarb.setSelected(false);
        graperb.setSelected(false);
        }
    }//GEN-LAST:event_waterrbActionPerformed

    private void applerbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applerbActionPerformed
        // TODO add your handling code here:
        if(applerb.isSelected()){
        chocorb.setSelected(false);
        latterb.setSelected(false);
        waterrb.setSelected(false);
        vanillarb.setSelected(false);
        graperb.setSelected(false);
        }
    }//GEN-LAST:event_applerbActionPerformed

    private void vanillarbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vanillarbActionPerformed
        // TODO add your handling code here:
        if(vanillarb.isSelected()){
            chocorb.setSelected(false);
            latterb.setSelected(false);
            waterrb.setSelected(false);
            graperb.setSelected(false);
            applerb.setSelected(false);
    }
    }//GEN-LAST:event_vanillarbActionPerformed

    private void graperbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_graperbActionPerformed
        // TODO add your handling code here:
        if(graperb.isSelected()){
        chocorb.setSelected(false);
        latterb.setSelected(false);
        waterrb.setSelected(false);
        applerb.setSelected(false);
        vanillarb.setSelected(false);
        
        }
    }//GEN-LAST:event_graperbActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Snack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Snack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Snack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Snack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Snack().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton applerb;
    private javax.swing.JButton cancelbtn;
    private java.awt.TextField changetf;
    private javax.swing.JRadioButton chocorb;
    private javax.swing.JButton clearbtn;
    private javax.swing.JRadioButton graperb;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private java.awt.Label label1;
    private javax.swing.JRadioButton latterb;
    private javax.swing.JLabel lbl1;
    private java.awt.Label lbl3;
    private java.awt.TextField moneytf;
    private javax.swing.JButton purchasebtn;
    private javax.swing.JRadioButton vanillarb;
    private javax.swing.JRadioButton waterrb;
    // End of variables declaration//GEN-END:variables
}
